const a = {
  uid: resUser.uid,
  email: resUser.email,
  emailVerified: resUser.emailVerified,
  full_name: resUser.displayName,
  photoURL: null,
  createdAt: resUser.createdAt,
  updatedAt: null,
  apiKey: resUser.apiKey,
  biography: null,
  bio_url: null,
  follows_viewer: false,
  hide_like_and_view_counts: false,
  is_private: false,
  is_verified: false,
  profile_pic_url: null,
  username: resUser.username,
};
